# Generated by Django 4.0.6 on 2022-08-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('zip', models.CharField(max_length=122)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=250, null=True)),
                ('p_category', models.CharField(blank=True, choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('FISH', 'Fish')], max_length=250, null=True)),
                ('p_discription', models.CharField(blank=True, max_length=250, null=True)),
                ('p_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('Firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
